apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: juhamyllari/todo-app:v2.8.1
        env:
          - name: BACKEND_PORT
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: BACKEND_PORT
          - name: FRONTEND_PORT
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: FRONTEND_PORT
          - name: STORAGE_DIR
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: STORAGE_DIR
          - name: IMAGE_FILENAME
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: IMAGE_FILENAME
          - name: IMAGE_SOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: IMAGE_SOURCE_URL
          - name: IMAGE_MAX_AGE
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: IMAGE_MAX_AGE
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: local-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: juhamyllari/todo-backend:v2.8.0
        envFrom:
          - secretRef:
              name: postgres-secret
        env:
          - name: BACKEND_PORT
            valueFrom:
              configMapKeyRef:
                name: log-configmap
                key: BACKEND_PORT
