apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: juhamyllari/logger:v1.7.1
