apiVersion: apps/v1
kind: Deployment
metadata:
  name: stamppong-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stamppong
  template:
    metadata:
      labels:
        app: stamppong
    spec:
      containers:
      - name: stamppong
        image: juhamyllari/stamppong:v1.11.0
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: local-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: juhamyllari/pingpong:v1.11.1
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: local-pvc
